# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Qt4_designer/rp.ui'
#
# Created: Sun Oct 20 15:14:55 2013
#      by: PyQt4 UI code generator 4.10
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(709, 368)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.toplevel_layout = QtGui.QVBoxLayout()
        self.toplevel_layout.setSizeConstraint(QtGui.QLayout.SetMinAndMaxSize)
        self.toplevel_layout.setObjectName(_fromUtf8("toplevel_layout"))
        self.panel_controls = QtGui.QHBoxLayout()
        self.panel_controls.setObjectName(_fromUtf8("panel_controls"))
        self.button_open_file = QtGui.QToolButton(self.centralwidget)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../icons/document-open.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_open_file.setIcon(icon)
        self.button_open_file.setToolButtonStyle(QtCore.Qt.ToolButtonFollowStyle)
        self.button_open_file.setObjectName(_fromUtf8("button_open_file"))
        self.panel_controls.addWidget(self.button_open_file)
        spacerItem = QtGui.QSpacerItem(6, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.panel_controls.addItem(spacerItem)
        self.button_play = QtGui.QToolButton(self.centralwidget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("../icons/media-playback-start.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_play.setIcon(icon1)
        self.button_play.setToolButtonStyle(QtCore.Qt.ToolButtonFollowStyle)
        self.button_play.setObjectName(_fromUtf8("button_play"))
        self.panel_controls.addWidget(self.button_play)
        self.button_pause = QtGui.QToolButton(self.centralwidget)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("../icons/media-playback-pause.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_pause.setIcon(icon2)
        self.button_pause.setToolButtonStyle(QtCore.Qt.ToolButtonFollowStyle)
        self.button_pause.setObjectName(_fromUtf8("button_pause"))
        self.panel_controls.addWidget(self.button_pause)
        self.button_stop = QtGui.QToolButton(self.centralwidget)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("../icons/media-playback-stop.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_stop.setIcon(icon3)
        self.button_stop.setToolButtonStyle(QtCore.Qt.ToolButtonFollowStyle)
        self.button_stop.setObjectName(_fromUtf8("button_stop"))
        self.panel_controls.addWidget(self.button_stop)
        spacerItem1 = QtGui.QSpacerItem(6, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.panel_controls.addItem(spacerItem1)
        self.button_boorkmarks_show = QtGui.QPushButton(self.centralwidget)
        self.button_boorkmarks_show.setAcceptDrops(True)
        self.button_boorkmarks_show.setCheckable(True)
        self.button_boorkmarks_show.setChecked(True)
        self.button_boorkmarks_show.setObjectName(_fromUtf8("button_boorkmarks_show"))
        self.panel_controls.addWidget(self.button_boorkmarks_show)
        self.button_bookmark_prev = QtGui.QToolButton(self.centralwidget)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("../icons/go-previous.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_bookmark_prev.setIcon(icon4)
        self.button_bookmark_prev.setToolButtonStyle(QtCore.Qt.ToolButtonFollowStyle)
        self.button_bookmark_prev.setObjectName(_fromUtf8("button_bookmark_prev"))
        self.panel_controls.addWidget(self.button_bookmark_prev)
        self.button_bookmark_next = QtGui.QToolButton(self.centralwidget)
        self.button_bookmark_next.setAcceptDrops(False)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8("../icons/go-next.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_bookmark_next.setIcon(icon5)
        self.button_bookmark_next.setToolButtonStyle(QtCore.Qt.ToolButtonFollowStyle)
        self.button_bookmark_next.setObjectName(_fromUtf8("button_bookmark_next"))
        self.panel_controls.addWidget(self.button_bookmark_next)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.panel_controls.addItem(spacerItem2)
        self.button_exit = QtGui.QToolButton(self.centralwidget)
        self.button_exit.setAcceptDrops(False)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8("../icons/system-log-out.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_exit.setIcon(icon6)
        self.button_exit.setToolButtonStyle(QtCore.Qt.ToolButtonFollowStyle)
        self.button_exit.setAutoRaise(False)
        self.button_exit.setObjectName(_fromUtf8("button_exit"))
        self.panel_controls.addWidget(self.button_exit)
        self.toplevel_layout.addLayout(self.panel_controls)
        self.panel_sliders = QtGui.QHBoxLayout()
        self.panel_sliders.setObjectName(_fromUtf8("panel_sliders"))
        self.panel_seek = QtGui.QVBoxLayout()
        self.panel_seek.setObjectName(_fromUtf8("panel_seek"))
        self.seek_slider = phonon.Phonon.SeekSlider(self.centralwidget)
        self.seek_slider.setObjectName(_fromUtf8("seek_slider"))
        self.panel_seek.addWidget(self.seek_slider)
        self.panel_seek_times = QtGui.QHBoxLayout()
        self.panel_seek_times.setContentsMargins(6, -1, 6, -1)
        self.panel_seek_times.setObjectName(_fromUtf8("panel_seek_times"))
        self.time_total = QtGui.QLabel(self.centralwidget)
        self.time_total.setObjectName(_fromUtf8("time_total"))
        self.panel_seek_times.addWidget(self.time_total)
        self.time_elapsed = QtGui.QLabel(self.centralwidget)
        self.time_elapsed.setAlignment(QtCore.Qt.AlignCenter)
        self.time_elapsed.setObjectName(_fromUtf8("time_elapsed"))
        self.panel_seek_times.addWidget(self.time_elapsed)
        self.time_left = QtGui.QLabel(self.centralwidget)
        self.time_left.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.time_left.setObjectName(_fromUtf8("time_left"))
        self.panel_seek_times.addWidget(self.time_left)
        self.panel_seek.addLayout(self.panel_seek_times)
        self.panel_sliders.addLayout(self.panel_seek)
        self.panel_volume = QtGui.QVBoxLayout()
        self.panel_volume.setObjectName(_fromUtf8("panel_volume"))
        self.volume_slider = phonon.Phonon.VolumeSlider(self.centralwidget)
        self.volume_slider.setOrientation(QtCore.Qt.Horizontal)
        self.volume_slider.setPageStep(10)
        self.volume_slider.setMuteVisible(True)
        self.volume_slider.setIconSize(QtCore.QSize(16, 16))
        self.volume_slider.setObjectName(_fromUtf8("volume_slider"))
        self.panel_volume.addWidget(self.volume_slider)
        self.volume_value = QtGui.QLabel(self.centralwidget)
        self.volume_value.setAlignment(QtCore.Qt.AlignCenter)
        self.volume_value.setObjectName(_fromUtf8("volume_value"))
        self.panel_volume.addWidget(self.volume_value)
        self.panel_sliders.addLayout(self.panel_volume)
        self.panel_speed = QtGui.QVBoxLayout()
        self.panel_speed.setObjectName(_fromUtf8("panel_speed"))
        self.speed_activated = QtGui.QCheckBox(self.centralwidget)
        self.speed_activated.setObjectName(_fromUtf8("speed_activated"))
        self.panel_speed.addWidget(self.speed_activated)
        self.speed_spinbox = QtGui.QDoubleSpinBox(self.centralwidget)
        self.speed_spinbox.setPrefix(_fromUtf8(""))
        self.speed_spinbox.setDecimals(2)
        self.speed_spinbox.setMinimum(0.1)
        self.speed_spinbox.setMaximum(10.0)
        self.speed_spinbox.setSingleStep(0.01)
        self.speed_spinbox.setProperty("value", 1.0)
        self.speed_spinbox.setObjectName(_fromUtf8("speed_spinbox"))
        self.panel_speed.addWidget(self.speed_spinbox)
        self.panel_sliders.addLayout(self.panel_speed)
        self.panel_sliders.setStretch(0, 1)
        self.toplevel_layout.addLayout(self.panel_sliders)
        self.panel_bookmarks = QtGui.QGroupBox(self.centralwidget)
        self.panel_bookmarks.setFlat(False)
        self.panel_bookmarks.setCheckable(False)
        self.panel_bookmarks.setObjectName(_fromUtf8("panel_bookmarks"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.panel_bookmarks)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.panel_bookmarks_buttons = QtGui.QVBoxLayout()
        self.panel_bookmarks_buttons.setObjectName(_fromUtf8("panel_bookmarks_buttons"))
        self.button_bookmark_update = QtGui.QToolButton(self.panel_bookmarks)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_bookmark_update.sizePolicy().hasHeightForWidth())
        self.button_bookmark_update.setSizePolicy(sizePolicy)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8("../icons/list-add.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_bookmark_update.setIcon(icon7)
        self.button_bookmark_update.setToolButtonStyle(QtCore.Qt.ToolButtonFollowStyle)
        self.button_bookmark_update.setObjectName(_fromUtf8("button_bookmark_update"))
        self.panel_bookmarks_buttons.addWidget(self.button_bookmark_update)
        self.button_bookmark_add = QtGui.QToolButton(self.panel_bookmarks)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_bookmark_add.sizePolicy().hasHeightForWidth())
        self.button_bookmark_add.setSizePolicy(sizePolicy)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8("../icons/document-save.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_bookmark_add.setIcon(icon8)
        self.button_bookmark_add.setToolButtonStyle(QtCore.Qt.ToolButtonFollowStyle)
        self.button_bookmark_add.setObjectName(_fromUtf8("button_bookmark_add"))
        self.panel_bookmarks_buttons.addWidget(self.button_bookmark_add)
        self.button_bookmark_del = QtGui.QToolButton(self.panel_bookmarks)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_bookmark_del.sizePolicy().hasHeightForWidth())
        self.button_bookmark_del.setSizePolicy(sizePolicy)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8("../icons/list-remove.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_bookmark_del.setIcon(icon9)
        self.button_bookmark_del.setToolButtonStyle(QtCore.Qt.ToolButtonFollowStyle)
        self.button_bookmark_del.setObjectName(_fromUtf8("button_bookmark_del"))
        self.panel_bookmarks_buttons.addWidget(self.button_bookmark_del)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.panel_bookmarks_buttons.addItem(spacerItem3)
        self.horizontalLayout_4.addLayout(self.panel_bookmarks_buttons)
        self.bookmarks_table = QtGui.QTableWidget(self.panel_bookmarks)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bookmarks_table.sizePolicy().hasHeightForWidth())
        self.bookmarks_table.setSizePolicy(sizePolicy)
        self.bookmarks_table.setRowCount(1)
        self.bookmarks_table.setColumnCount(3)
        self.bookmarks_table.setObjectName(_fromUtf8("bookmarks_table"))
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.bookmarks_table.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.bookmarks_table.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.bookmarks_table.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.bookmarks_table.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        self.bookmarks_table.setItem(0, 1, item)
        item = QtGui.QTableWidgetItem()
        self.bookmarks_table.setItem(0, 2, item)
        self.bookmarks_table.horizontalHeader().setStretchLastSection(True)
        self.bookmarks_table.verticalHeader().setStretchLastSection(False)
        self.horizontalLayout_4.addWidget(self.bookmarks_table)
        self.toplevel_layout.addWidget(self.panel_bookmarks)
        self.toplevel_layout.setStretch(2, 1)
        self.horizontalLayout_5.addLayout(self.toplevel_layout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 709, 24))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFichier = QtGui.QMenu(self.menubar)
        self.menuFichier.setObjectName(_fromUtf8("menuFichier"))
        self.menu_propos = QtGui.QMenu(self.menubar)
        self.menu_propos.setObjectName(_fromUtf8("menu_propos"))
        self.menuSignets = QtGui.QMenu(self.menubar)
        self.menuSignets.setObjectName(_fromUtf8("menuSignets"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.action_propos = QtGui.QAction(MainWindow)
        self.action_propos.setObjectName(_fromUtf8("action_propos"))
        self.actionNouveau = QtGui.QAction(MainWindow)
        self.actionNouveau.setObjectName(_fromUtf8("actionNouveau"))
        self.actionOuvrir = QtGui.QAction(MainWindow)
        self.actionOuvrir.setObjectName(_fromUtf8("actionOuvrir"))
        self.actionEnregistrer = QtGui.QAction(MainWindow)
        self.actionEnregistrer.setObjectName(_fromUtf8("actionEnregistrer"))
        self.actionEnregistrer_sous = QtGui.QAction(MainWindow)
        self.actionEnregistrer_sous.setObjectName(_fromUtf8("actionEnregistrer_sous"))
        self.actionFichiers_r_cents = QtGui.QAction(MainWindow)
        self.actionFichiers_r_cents.setObjectName(_fromUtf8("actionFichiers_r_cents"))
        self.actionFermer = QtGui.QAction(MainWindow)
        self.actionFermer.setObjectName(_fromUtf8("actionFermer"))
        self.actionQuitter = QtGui.QAction(MainWindow)
        self.actionQuitter.setObjectName(_fromUtf8("actionQuitter"))
        self.actionAide = QtGui.QAction(MainWindow)
        self.actionAide.setObjectName(_fromUtf8("actionAide"))
        self.actionNouveau_2 = QtGui.QAction(MainWindow)
        self.actionNouveau_2.setObjectName(_fromUtf8("actionNouveau_2"))
        self.actionTout_supprimer = QtGui.QAction(MainWindow)
        self.actionTout_supprimer.setObjectName(_fromUtf8("actionTout_supprimer"))
        self.actionAfficher = QtGui.QAction(MainWindow)
        self.actionAfficher.setObjectName(_fromUtf8("actionAfficher"))
        self.menuFichier.addAction(self.actionNouveau)
        self.menuFichier.addAction(self.actionOuvrir)
        self.menuFichier.addAction(self.actionFichiers_r_cents)
        self.menuFichier.addSeparator()
        self.menuFichier.addAction(self.actionEnregistrer)
        self.menuFichier.addAction(self.actionEnregistrer_sous)
        self.menuFichier.addSeparator()
        self.menuFichier.addAction(self.actionFermer)
        self.menuFichier.addAction(self.actionQuitter)
        self.menu_propos.addAction(self.actionAide)
        self.menu_propos.addSeparator()
        self.menu_propos.addAction(self.action_propos)
        self.menuSignets.addAction(self.actionAfficher)
        self.menuSignets.addSeparator()
        self.menuSignets.addAction(self.actionNouveau_2)
        self.menuSignets.addAction(self.actionTout_supprimer)
        self.menubar.addAction(self.menuFichier.menuAction())
        self.menubar.addAction(self.menuSignets.menuAction())
        self.menubar.addAction(self.menu_propos.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.button_exit, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.close)
        QtCore.QObject.connect(self.button_boorkmarks_show, QtCore.SIGNAL(_fromUtf8("released()")), self.panel_bookmarks.hide)
        QtCore.QObject.connect(self.button_boorkmarks_show, QtCore.SIGNAL(_fromUtf8("pressed()")), self.panel_bookmarks.show)
        QtCore.QObject.connect(self.actionQuitter, QtCore.SIGNAL(_fromUtf8("activated()")), MainWindow.close)
        QtCore.QObject.connect(self.actionAfficher, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.panel_bookmarks.hide)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.button_open_file.setText(_translate("MainWindow", "Ouvrir...", None))
        self.button_play.setText(_translate("MainWindow", "Play", None))
        self.button_pause.setText(_translate("MainWindow", "Pause", None))
        self.button_stop.setText(_translate("MainWindow", "Stop", None))
        self.button_boorkmarks_show.setText(_translate("MainWindow", "Signets", None))
        self.button_bookmark_prev.setText(_translate("MainWindow", "Précédent", None))
        self.button_bookmark_next.setText(_translate("MainWindow", "Suivant", None))
        self.button_exit.setText(_translate("MainWindow", "Fermer", None))
        self.time_total.setText(_translate("MainWindow", "--:--", None))
        self.time_elapsed.setText(_translate("MainWindow", "--:--", None))
        self.time_left.setText(_translate("MainWindow", "--:--", None))
        self.volume_value.setText(_translate("MainWindow", "100%", None))
        self.speed_activated.setText(_translate("MainWindow", "vitesse", None))
        self.panel_bookmarks.setTitle(_translate("MainWindow", "Signets", None))
        self.button_bookmark_update.setText(_translate("MainWindow", "add", None))
        self.button_bookmark_add.setText(_translate("MainWindow", "update", None))
        self.button_bookmark_del.setText(_translate("MainWindow", "remove", None))
        self.bookmarks_table.setSortingEnabled(True)
        item = self.bookmarks_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Temps", None))
        item = self.bookmarks_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Nom", None))
        item = self.bookmarks_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Commentaire", None))
        __sortingEnabled = self.bookmarks_table.isSortingEnabled()
        self.bookmarks_table.setSortingEnabled(False)
        self.bookmarks_table.setSortingEnabled(__sortingEnabled)
        self.menuFichier.setTitle(_translate("MainWindow", "Fichier", None))
        self.menu_propos.setTitle(_translate("MainWindow", "À propos", None))
        self.menuSignets.setTitle(_translate("MainWindow", "Signets", None))
        self.action_propos.setText(_translate("MainWindow", "À propos", None))
        self.actionNouveau.setText(_translate("MainWindow", "Nouveau...", None))
        self.actionOuvrir.setText(_translate("MainWindow", "Ouvrir...", None))
        self.actionEnregistrer.setText(_translate("MainWindow", "Enregistrer", None))
        self.actionEnregistrer_sous.setText(_translate("MainWindow", "Enregistrer sous...", None))
        self.actionFichiers_r_cents.setText(_translate("MainWindow", "Fichiers récents...", None))
        self.actionFermer.setText(_translate("MainWindow", "Fermer", None))
        self.actionQuitter.setText(_translate("MainWindow", "Quitter", None))
        self.actionAide.setText(_translate("MainWindow", "Aide", None))
        self.actionNouveau_2.setText(_translate("MainWindow", "Nouveau", None))
        self.actionTout_supprimer.setText(_translate("MainWindow", "Tout supprimer", None))
        self.actionAfficher.setText(_translate("MainWindow", "Afficher", None))

from PyQt4 import phonon
